services:
  db:
    image: mdillon/postgis:9.4
    container_name: gps_collector_db
    environment:
      POSTGRES_DB: gps_collector
      POSTGRES_PASSWD: gps_collector
      POSTGRES_USER: gps_collector
    ports:
      - "5432"
  test_db:
    image: mdillon/postgis:9.4
    container_name: gps_collector_db_test
    environment:
      POSTGRES_DB: gps_collector
      POSTGRES_PASSWD: gps_collector
      POSTGRES_USER: gps_collector
    ports:
      - "5432"
    volumes:
      - /tmp:/tmp
  web:
    volumes:
      - .:/gps_collector
    build: .
    ports:
      - "4567:4567"
    depends_on:
      - db
    restart: on-failure
    stdin_open: true
    tty: true
