# frozen_string_literal: true

source 'https://rubygems.org'

gem 'activerecord'
gem 'activerecord-postgis-adapter'
gem 'bootstrap'
gem 'pg'
gem 'pry'
gem 'puma'
gem 'rack'
gem 'rack-test'
gem 'rake'
gem 'rgeo-geojson'
gem 'rspec'
gem 'rubocop', '~> 1.19'
gem 'sequel'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'yard'
